### ISSUE TITLE
[Discussion] Do we need to use map instead of array when declare Workflow CRD?

### ISSUE THREAD

**Issue by linxuyalun** [tass-io/tass-operator#1]
Here is an example of Workflow CRD:

```yaml
apiVersion: serverless.tass.io/v1alpha1
kind: Workflow
metadata:
  name: workflow-sample
spec:
  environment: Golang
  domain: sail
  spec:
  # Note that it is an array
  - name: flow-sample
    function: function-sample
    inputs:
    - hi
    - hey
    outputs:
    - exit
    - bye
    statement: switch
    condition:
      type: string
      operator: eq
      comparision: money
      destination:
        isTrue: [exit]
        isFalse: [bye]
```

And we prefer declaring nested map instead, e.g.:

```yaml
# ...
spec:
  environment: Golang
  domain: sail
  spec:
    flow-sample1:
      function: function-sample
      inputs:
      - hi
      - hey
      outputs:
      - exit
      - bye
      statement: switch
      condition:
        type: string
        operator: eq
        comparision: money
        destination:
          isTrue: [exit]
          isFalse: [bye]
    flow-sample2:
      function: function-sample
      inputs:
      - hi
      - hey
      outputs:
      - exit
      - bye
      statement: switch
      condition:
        type: string
        operator: eq
        comparision: money
        destination:
          isTrue: [exit]
          isFalse: [bye]
```

So I have checked some materials about that and found it not natural to implement. Note that CRD uses OpenAPI to validate the fields which means you should define the field name first instead of the uncertain field name.

So if we want to achieve such an effect, we can implement that by using `unstructured.Unstructured`, here is an [example](https://github.com/vshn/espejo/blob/master/api/v1alpha1/syncconfig_types.go#L20).

I don't think that it's a good idea to use this struct cause it seems to break the ability of validation.

I will go deeper about it and comment below when finding something new.

What do you guys think?
